version: '2'
services:
  starlord:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - vault
      - rabbit
    environment:
      - NODE_ENV=development
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOSTNAME=rabbit
      - VAULT_ENDPOINT=http://vault:8200
      - VAULT_TOKEN=f3b7d5b3-5ebf-4474-a312-bb98e5e240c0

  starlord_test:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "/wait.sh rabbit:5672 -t 30 && sleep 5 && npm test"
    links:
      - vault
      - rabbit
    environment:
      - NODE_ENV=development
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOSTNAME=rabbit
      - VAULT_ENDPOINT=http://vault:8200
      - VAULT_TOKEN=f3b7d5b3-5ebf-4474-a312-bb98e5e240c0

  vault:
    image: vault:0.6.4
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=f3b7d5b3-5ebf-4474-a312-bb98e5e240c0
    ports:
      - "8200:8200"

  rabbit:
    image: rabbitmq:3.4.3-management
    ports:
      - "15672:15672"

  rabbitpuppy:
    image: meltwater/rabbit-puppy:latest
    links:
      - rabbit
    volumes:
      - ./config:/config
    command: apply -b http://rabbit:15672/ -u guest -p guest -c /config/rabbit-config.yaml -w 60
